[FileDialog]
history=file:///home/simon/programmation/prim_s2/doc, file:///home/simon/.config/hypr/wallpapers, file:///home/simon/cloud/pcloud/priv\xc3\xa9/bd, file:///home/simon/cloud/pcloud/priv\xc3\xa9, file:///home/simon/cloud/nextcloud, file:///home/simon/cloud/mdp
lastVisited=file:///home/simon/cloud/mdp
qtVersion=5.15.13
shortcuts=file:, file:///home/simon
sidebarWidth=87
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
