[gdrive-simonbelier29]
type = drive
scope = drive
token = {"access_token":"ya29.a0Ad52N39N2bo6RXVTXNp59PVhI2rJ5s941gjAOu-umnllmU7ydcG8gnD2Xuv1y38MRUfdrFkY9KFYeDraE7ZR1U_aVZEV77m9K1rqdI9mc7WENVzrJ--fz2PSCXR8qgwiZMWcaQbWSYoGmRQ7KNlIENsl9-IV92ndjSpeOAaCgYKAecSARMSFQHGX2Miq3SR6-ZM0rdoE3_45eFCmw0173","token_type":"Bearer","refresh_token":"1//03FelWhCfCLP4CgYIARAAGAMSNwF-L9Irvj6D5TXpoclHZqlA88iZPbvTau9UDrCFSldmOflZdHQAXnce2NUhU7SdLtoD8PTHfUY","expiry":"2024-04-11T02:26:02.89515127+02:00"}
team_drive = 

[nextcloud-good_cloud]
type = webdav
url = https://cloud.lebib.org/
vendor = nextcloud
user = BigOuden
pass = 3MI1MuijpOUFhG1lZNsyiDUvE86H_XPnux-spaH63CqLsXs

[pcloud]
type = pcloud
hostname = eapi.pcloud.com
token = {"access_token":"AKFbZDnONSzyJXpmZphMl7kZQydGAaA3DxSr4kPRD0NMKFIODmlV","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}

